apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wazuh.fullname" . }}-integrations
  labels:
  {{- include "wazuh.labels" . | nindent 4 }}
data:
{{ tpl (.Files.Glob "files/integrations/*").AsConfig . | indent 2 }}