apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wazuh.fullname" . }}-indexer-cred
  labels:
  {{- include "wazuh.labels" . | nindent 4 }}
data:
  password: {{ required "indexer.password is required" .Values.cred.indexer.password | b64enc }}
  username: {{  required "indexer.username is required" .Values.cred.indexer.username | b64enc }}