apiVersion: v1
kind: Service
metadata:
  name: indexer
  labels:
    app: wazuh-indexer
spec:
  type: {{ .Values.indexer.type }}
  selector:
    app: wazuh-indexer
  ports:
    - name: indexer-rest
      port: 9200
      targetPort: 9200