apiVersion: v1
kind: Service
metadata:
  name: wazuh
  labels:
    app: wazuh-manager
spec:
  selector:
    app: wazuh-manager
    node-type: master
  ports:
  {{- .Values.wazuh.ports | toYaml | nindent 2 }}
  #  - name: registration
  #   nodePort: 30002
  #   port: 1515
  #   targetPort: 1515
  # - name: api
  #   nodePort: 30003
  #   port: 55000
  #   targetPort: 55000
  type: {{ .Values.wazuh.type }}